builds:
- main: ./cmd/go-cli-github
  ldflags:
  - >
    -s -w
    -X "main.commit={{.Commit}}"
    -X "main.date={{.Date}}"
    -X "main.goVersion={{.Env.GOVERSION}}"
    -X "main.projectName={{.ProjectName}}"
    -X "main.version={{.Version}}"
  env:
  - CGO_ENABLED=0
sboms:
- artifacts: archive
signs:
- cmd: cosign
  signature: "${artifact}.sig"
  certificate: "${artifact}.pem"
  args:
  - "sign-blob"
  - "--output-signature=${signature}"
  - "--output-certificate=${certificate}"
  - "${artifact}"
  - "--yes"
  artifacts: checksum
