version: 2
builds:
- &buildDefinition
  id: go-cli-github
  binary: go-cli-github
  main: ./cmd/go-cli-github
  ldflags:
  - >
    -s -w
    -X "main.commit={{.Commit}}"
    -X "main.date={{.Date}}"
    -X "main.projectName={{.ProjectName}}"
    -X "main.version=v{{.Version}}"
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
- <<: *buildDefinition
  id: another-binary
  binary: another-binary
  main: ./cmd/another-binary

changelog:
  use: github-native

dockers_v2:
- id: go-cli-github
  ids:
  - go-cli-github
  images:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/go-cli-github"
  tags:
  - "v{{ .Version }}"
  - latest
  build_args:
    BINARY: go-cli-github
- id: another-binary
  ids:
  - another-binary
  images:
  - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}/another-binary"
  tags:
  - "v{{ .Version }}"
  - latest
  build_args:
    BINARY: another-binary

release:
  extra_files:
  - glob: ./sbom.spdx.json
    name_template: "{{ .ProjectName }}.v{{ .Version }}.sbom.spdx.json"

checksum:
  name_template: checksums.txt
