name: dependency review
on:
  pull_request:
    branches:
    - main
  merge_group:
    types:
    - checks_requested
permissions: {}
jobs:
  dependency-review:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/dependency-review-action@40c09b7dc99638e5ddb0bfd91c1673effc064d8a # v4.8.1
      with:
        config-file: .github/dependency-review-config.yaml
